import { Metadata } from "next"
import classNames from "classnames"
import { PropsWithChildren } from "react"
import { GeistSans } from "geist/font"
import "./globals.css"
import { TopNavBar } from "@components/components/navbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang="en">
      <body
        className={classNames(
          GeistSans.className,
          "h-screen",
          "bg-gradient-to-b",
          "from-sky-50",
          "to-gray-100",
        )}
      >
        <TopNavBar />
        {props.children}
      </body>
    </html>
  )
}
